name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh  # This will create .ssh directory on GitHub Runner machine
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            cd ~/task-manager/client
            docker pull rawattech/task-manager-client:latest
            docker stop client-container || true
            docker rm client-container || true
            docker run -d --name client-container -p 5173:5173 rawattech/task-manager-client:latest

            cd ~/task-manager/server
            docker pull rawattech/task-manager-server:latest
            docker stop server-container || true
            docker rm server-container || true
            docker run -d --name server-container -p 5000:5000 rawattech/task-manager-server:latest

            sudo systemctl restart nginx
