name: Server CI/CD

on:
  push:
    branches: [ main ]
    paths: [ 'server/**' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install deps & Build
        working-directory: ./server
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Docker Build & Push
        run: |
          docker build -t rawattech/task-manager-server:latest ./server
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push rawattech/task-manager-server:latest
